# Generated by Django 5.2.5 on 2025-08-26 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='full_name',
            field=models.CharField(default='Unknown', max_length=50),
        ),
        migrations.AddField(
            model_name='manager',
            name='full_name',
            field=models.CharField(default='Unknown', max_length=50),
        ),
        migrations.AddField(
            model_name='staff',
            name='full_name',
            field=models.CharField(default='Unknown', max_length=50),
        ),
    ]
