# Generated by Django 5.2.5 on 2025-08-27 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_alter_customer_user_alter_manager_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='added_on',
            field=models.DateField(auto_now_add=True),
        ),
    ]
