# Generated by Django 5.2.5 on 2025-08-28 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_alter_customer_added_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='added_on',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='manager',
            name='added_on',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='added_on',
            field=models.DateField(auto_now_add=True),
        ),
    ]
