# Generated by Django 5.2.5 on 2025-08-28 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_alter_department_added_on_alter_manager_added_on_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='department',
            field=models.CharField(choices=[('HR', 'HR'), ('Finance', 'Finance'), ('Engineering', 'Engineering'), ('Marketing', 'Marketing'), ('Sales', 'Sales'), ('Support', 'Support')], default='HR', max_length=50),
        ),
    ]
