# Generated by Django 5.2.5 on 2025-08-28 06:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_alter_manager_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='department',
            field=models.ForeignKey(default='HR', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managers', to='crm.department'),
        ),
    ]
