# Generated by Django 5.2.5 on 2025-08-28 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_alter_manager_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='skill',
            field=models.CharField(default='unknown', max_length=40),
        ),
    ]
