# Generated by Django 5.2.5 on 2025-08-28 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0009_staff_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='user_photos/'),
        ),
    ]
